name: Create Manual Approval Issue
author: toppulous
branding:
  color: purple
  icon: check-circle
description: Creates an issue that will be used for manual approvals between stages in a CI/CD pipeline.
inputs:
  label:
    description: The label to attach to the issue - should be unique per stage, and should not be used outside of CI/CD
    required: true
  title:
    description: Title to assign the issue
    default: '[Github Actions] Manual Approval Required'
    required: false
  body:
    description: Body to assign to the issue
    default: 'Closing this issue will approve all changes listed in comments to the next stage'
    required: false
  github-token:
    description: The gitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  repo:
    description: Other repo
    default: ${{ github.context.repo.repo }}
    required: false
  assignee:
    description: Assignee
    default: ${{ github.context.actor }}
    required: false
outputs:
  issue-number:
    description: 'Number of the issue created (or found, if one already exists with the given label)'
runs:
  using: node12
  main: index.js
