on:
  push:
    branches: master

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Create initial issue
        id: issue1
        uses: sky-distribution/create-manual-approval-issue@master
        with:
          label: dev-approval
      - run: |
          echo 'First issue id ${{ steps.issue1.outputs.issue-number }}'
      - name: Get initial issue
        id: issue2
        uses: sky-distribution/create-manual-approval-issue@master
        with:
          label: dev-approval
      - run: |
          echo 'Second issue id ${{ steps.issue2.outputs.issue-number }}'
      - if: steps.issue1.outputs.issue-number != steps.issue2.outputs.issue-number
        uses: actions/github-script@v1
        with:
          script: |
            throw 'Expected ids to be equal'
      - uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ steps.issue1.outputs.issue-number }}
          comment: Closing integration test issue


